# Generated by Django 4.0 on 2021-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_uid_to_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='contacts',
            field=models.ManyToManyField(related_name='messages', to='contacts.Contact'),
        ),
    ]
