# Generated by Django 4.0 on 2021-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='temporalCode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
